**Introduction to Pandas**

**Pandas Python Library**

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**
Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame: **A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.
2.Clean datasets, for example, by dealing with missing values.
3.Tidy datasets by reshaping their structure into a suitable format for analysis.
4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.
5.Visualize datasets and uncover insights.Pandas Python Library

**Importing data in pandas**

In [ ]:
import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [ ]:
df=pd.read_excel("/content/Student Detalis.xlsx")

In [ ]:
df.head()

,Student Name,Student Name.1,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,java,phython,chemistry,physics,DS
1,Rena,10.0,CSM,90,95,88,87,80
2,Radhi,11.0,CSM,80,86,80,77,70
3,Rocky,12.0,CSM,100,95,94,80,88
4,Vijay,13.0,CSM,88,70,60,80,79

In [ ]:
df.tail()

,Student Name,Student Name.1,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
5,Naveen,14.0,CSM,80,60,70,77,87
6,Guna,15.0,CSM,70,50,50,45,79
7,Arjun,16.0,CSM,95,90,88,80,78
8,Anita,17.0,CSM,60,70,80,90,100
9,Ravi,19.0,CSM,66,70,60,80,50

In [ ]:
df.describe()

       Student Name.1
count        9.000000
mean        14.111111
std          2.934469
min         10.000000
25%         12.000000
50%         14.000000
75%         16.000000
max         19.000000

In [ ]:
df.columns

Index(['Student Name', 'Student Name.1', 'Branch', 'Subjects', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

**Importing text file**

In [ ]:
-